name: reteach
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask=2.3.3
  - flask-socketio=5.3.6
  - eventlet=0.33.3
  - requests=2.31.0
  - numpy=1.26.4
  - scipy=1.13.1
  - pip
  - pip:
    - langchain-ollama
    - langchain-core
    - openai==1.30.1
    - python-dotenv
